#!/bin/bash
set -eu

if [ $# -eq 0 ]; then cat << EOF

Encodes a previously captured NTSC video from 720x480/PCM/MPEG to 720x540/AAC/h.264

${0} <capture.mpg>

The encoded file is output to the same directory as the captured video,
and uses the same name, but with the extension changed to mp4.

EOF
exit 1; fi

INFILE="${1}"
DIRNAME=$(dirname "${INFILE}")
BASENAME=$(basename ${INFILE})
BASENAME=${BASENAME%.*}

ffmpeg -i ${INFILE} \
    -c:v libx264 -vf "readvitc,yadif,scale=720x540" -b:v 4M \
    -c:a libfdk_aac -b:a 128k \
    -y "${DIRNAME}/${BASENAME}.mp4"
