#!/bin/bash
set -eu

if [ $# -eq 0 ]; then cat << EOF

Transcodes a previously captured NTSC video from 720x480/MPEG2 to 720x540/AAC/H.264

${0} [-s nn:nn] [-t nn:nn] <capture.mpg> [<output.mp4>]

Unless the second argument is given to specify the output file name,
the transcoded video is put in the same directory as the captured video,
and uses the same name with the extension changed to mp4.

-s  Start timecode
-t  End timecode

EOF
    exit 1
fi

START=""
DURATION=""
while getopts ":s:t:" opt; do case $opt in
    s) START="-ss ${OPTARG}"
    ;;
    t) DURATION="-to ${OPTARG}"
    ;;
esac done
shift $((OPTIND-1))

INFILE="${1}"
if [ $# -eq 1 ]; then
    DIRNAME=$(dirname "${INFILE}")
    BASENAME=$(basename "${INFILE}")
    OUTFILE="${DIRNAME}/${BASENAME%.*}.mp4"
else
    OUTFILE="${2}"
fi

ffmpeg \
    $START \
    -i ${INFILE} \
    -c:v libx264 \
        -b:v 8M \
        -vf "yadif" \
        -preset medium -tune grain \
        -pix_fmt yuv420p \
    -c:a aac \
    -metadata creation_time="$(date --iso-8601=seconds)" \
    -movflags faststart \
    $DURATION \
    -y "${OUTFILE}"
