#!/bin/bash
set -eu

if [ $# -eq 0 ]; then cat << EOF

Transcodes an interlaced NTSC video to AAC/x264.

${0} [options] input.mpg [output.mkv]

    Options:
    -s [nn:[nn:]]nn     Start transcoding from this timecode
    -t [nn:[nn:]]nn     End transcoding at this timecode

If no output file name is given, it defaults to a similarly named
MKV in the working directory.

Roughly 1GB is produced for each hour of transcoded video.

EOF
    exit 1
fi

StartTime=""
EndTime=""
while getopts ":s:t:" opt; do case $opt in
    s) StartTime="-ss ${OPTARG}"
    ;;
    t) EndTime="-t ${OPTARG}"
    ;;
esac done
shift $((OPTIND-1))

Input="${1}"
if [ $# -eq 1 ]; then
    Basename=$(basename "${Input}")
    Output="${Basename%.*}.mkv"
else
    Output="${2}"
fi

ffmpeg \
    $EndTime \
    -i "${Input}" \
    -c:a aac \
    -c:v libx264 \
        -vf "yadif" \
        -crf 23 \
        -preset veryslow \
    -metadata creation_time="$(date --iso-8601=seconds)" \
    -movflags +faststart \
    $StartTime \
    "${Output}"
