#!/bin/bash
set -eu
source $(dirname $(readlink -f "${0}"))/.rc.sh

VIDEO_ARGS="device=${VIDEO_DEVICE}"
AUDIO_ARGS="alsa:adevice=hw.${ALSA_ID},0:forceaudio:immediatemode=0:audiorate=48000"
mplayer tv:// -tv "${VIDEO_ARGS}:${AUDIO_ARGS}" -framedrop -autosync 10000 -fps 30 -aspect 4:3
