#!/bin/bash
set -eu

if  [ $# -eq 0 ]; then cat << EOF

Captures A/V to an MPEG2 file.

${0} [options] <capture.mpg>

    -t <[[HH:]MM:]SS>
    Duration of the captured video file.
    Default: forever (until canceled)

    This duration won't match the duration displayed on your VCR if the tape
    has empty segments. VCRs don't count empty segments as time-played.

    When in doubt add a few minutes, or use the tape's entire length-capacity.

EOF
exit 1; fi

DURATION=""
while getopts ":t:" opt; do case $opt in
    t) DURATION="-t ${OPTARG}"
    ;;
esac done
shift $((OPTIND-1))
OUTFILE="${1}"
source $(dirname $(readlink -f "${0}"))/.init

# the video bitrate is brought down from the device's 16MB to 8MB in order to be sensible without losing any detail.
ffmpeg \
    -f v4l2 \
        -thread_queue_size 2048 \
        -i ${_VIDEO_DEVICE} \
    -f alsa \
        -thread_queue_size 2048 \
        -i hw:${_ALSA_ID},0 \
    -c:v mpeg2video -c:a mp2 \
        -b:v 8M \
        -pix_fmt yuv420p \
        -aspect ${_VIDEO_ASPECT} \
        ${DURATION} \
        -y "${OUTFILE}"
