#!/bin/bash
set -eu

if  [ $# -eq 0 ]; then cat << EOF

Captures NTSC video to an MPEG-TS file.

${0} [options] <capture.mpg>

    -t <[[HH:]MM:]SS>
    Duration of time to capture.
    Default: forever

EOF
exit 1; fi

DURATION=""
while getopts ":a:t:" opt; do case $opt in
    t) DURATION="-t ${OPTARG}"
    ;;
esac done
shift $((OPTIND-1))
OUTFILE="${1}"

# the video bitrate is brought down to 8M in order to be sensible without losing any detail.
source $(dirname $(readlink -f "${0}"))/.rc.sh
ffmpeg \
    -f v4l2 -i "${VIDEO_DEVICE}" \
    -f alsa -i hw:${ALSA_ID},0 \
    -f mpegts -aspect 4:3 -b:v 8M ${DURATION} -y "${OUTFILE}"

