#!/bin/bash
source $(dirname $(readlink -f "${0}"))/.init
echo

echo ===== VIDEO =====
echo

v4l2-ctl -d ${_VIDEO_DEVICE} --all
echo

v4l2-ctl -d ${_VIDEO_DEVICE} --list-formats
echo

echo ===== AUDIO =====
echo

cat /proc/asound/card${_ALSA_ID}/stream0
echo

amixer -c ${_ALSA_ID} contents
echo

amixer -c ${_ALSA_ID} scontents
echo
