#!/bin/bash
source $(dirname $(readlink -f "${0}"))/.init

v4l2-ctl -d ${_VIDEO_DEVICE} --all

cat /proc/asound/card${_ALSA_ID}/stream0
amixer -c ${_ALSA_ID} contents
amixer -c ${_ALSA_ID} scontents

