#!/bin/bash
# prints info about the device
set -eu
source $(dirname $(readlink -f "${0}"))/.init

cat << EOF

Video
Device:     ${_VIDEO_DEVICE}
Input:      ${_VIDEO_INPUT_ID} ${_VIDEO_INPUT_NAME}

Audio
ALSA ID:    ${_ALSA_ID}
Signal:     ${_VIDEO_NORM}

EOF
