#!/bin/bash
set -eu
source $(dirname $(readlink -f "${0}"))/.rc.sh

mplayer tv:// -tv "device=${VIDEO_DEVICE}:normid=1:alsa:adevice=hw.${ALSA_ID},0:forceaudio:immediatemode=0:audiorate=48000" -vf yadif -aspect 4:3
