#!/bin/bash
set -eu
source $(dirname $(readlink -f "${0}"))/.init

usage(){ cat << EOF

Sets various controls on the device and finetunes the device's settings.

${0} selection [selection ...]

Inputs:
    composite
    svideo

Signals:
    ntsc        North America
    pal         Europe (most)
    secam       France

Specifying a number as the selection will set the signal by ID.
Supported signal IDs can seen via:

$ v4l2-ctl -d ${_VIDEO_DEVICE} --list-standards -k

EOF
    exit 1
}

if [ $# -eq 0 ]; then usage; fi
ctl(){
    v4l2-ctl -d ${_VIDEO_DEVICE} $*
}

V4L2_CTL_ARGS=""
for opt in $*; do case $opt in
    composite) ctl -i 0; ;;
    svideo)
        ctl -i 1
        ctl -c sharpness=0
    ;;

    ntsc)
        ctl -s 1
        ctl -c sharpness=5
    ;;
    pal) ctl -s 5; ;;

    # set standard id by default
    *)
        int='^[0-9]+$'
        if [[ $opt =~ $int ]]; then
            ctl -s $opt
        else
            usage
        fi
    ;;

esac; done
