#!/bin/bash
# initializes the capture device.
# this is also sourced by the other scripts.

INITIALIZED=0
lsusb | grep 1c88:003c >/dev/null || INITIALIZED=1
if [ ! $INITIALIZED ]; then
    sudo somagic-init
fi

