#!/bin/bash
set -eu

if  [ $# -eq 0 ]; then cat << EOF

Captures NTSC video to an MPEG-TS file.

${0} <capture.mpg> [options]

    -a <alsa-id>
    ALSA hardware ID for the microphone.
    Default: 0

    -t <[[HH:]MM:]SS>
    Duration of time to capture.
    Default: forever

EOF
exit 1; fi

OUTFILE="${1}"
ALSA_ID="0"
DURATION=""

while getopts ":a:t:" opt; do case $opt in
    a) ALSA_ID="${OPTARG}"
    ;;
    t) DURATION="-t ${OPTARG}"
    ;;
esac done

# the video bitrate is brought down to 8M in order to be sensible without losing any detail.
source $(dirname $(readlink -f "${0}"))/.init.sh
ffmpeg \
    -f v4l2 -framerate 29.97 -video_size 720x480 -i "${VIDEO_DEVICE}" \
    -f alsa -i hw:${ALSA_ID} \
    -f mpegts -aspect 4:3 -b:v 5M ${DURATION} -y "${OUTFILE}"

